
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Sep 03 20:10:39 CEST 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAP = 17;
  public static final int LOGAND = 43;
  public static final int CONST = 23;
  public static final int GREATEQUAL = 30;
  public static final int NOTEQUAL = 29;
  public static final int CONTINUE = 35;
  public static final int LPAREN = 7;
  public static final int GREATER = 32;
  public static final int SEMI = 5;
  public static final int FILTER = 56;
  public static final int FOR = 37;
  public static final int MINUS = 12;
  public static final int CHARACTER = 50;
  public static final int RPAREN = 8;
  public static final int LESSEQUAL = 31;
  public static final int BOOL = 48;
  public static final int COMMA = 16;
  public static final int INC = 38;
  public static final int EQUALEQUAL = 28;
  public static final int DIV = 14;
  public static final int LESSER = 33;
  public static final int PLUS = 11;
  public static final int IF = 21;
  public static final int DOT = 26;
  public static final int FINDANY = 18;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int EQUAL = 9;
  public static final int NEW = 40;
  public static final int error = 1;
  public static final int MUL = 13;
  public static final int NUMBER = 47;
  public static final int MOD = 15;
  public static final int IDENT = 49;
  public static final int BREAK = 34;
  public static final int CONTAINS = 55;
  public static final int VOID = 20;
  public static final int LBRACK = 24;
  public static final int FOREACH = 53;
  public static final int COLON = 6;
  public static final int LBRACE = 3;
  public static final int ELSE = 22;
  public static final int READ = 36;
  public static final int RBRACK = 25;
  public static final int INRANGE = 54;
  public static final int GOTO = 46;
  public static final int FINAL = 52;
  public static final int WHILE = 44;
  public static final int LOGOR = 42;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int QUESTION = 27;
  public static final int DEC = 39;
  public static final int MAX = 51;
  public static final int DO = 45;
  public static final int LENGTH = 41;
  public static final int PRINT = 19;
}

